name: CI

# Controls when the action will run.
on: push

jobs:
  
  # Flake
  flake:
    name: Run flake8 linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out plugin repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          flake8: true
          flake8_dir: plugin.video.catchuptvandmore/
          
  # Test add-on python files
  test-plugin-modules:
    name: Load each Python files of the addon to detect errors
    needs: flake
    runs-on: ubuntu-latest
    steps:
      - name: Check out plugin repository
        uses: actions/checkout@v2
        with:
          path: plugin
      - name: Check out simulator repository
        uses: actions/checkout@v2
        with:
          path: simulator
          repository: Catch-up-TV-and-More/catchuptvandmore-test
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: simulator
        run: pip install -r requirements.txt
      - name: Start catchuptvandmore-test with test_modules config
        working-directory: simulator
        run: python main.py --test-modules -a ../plugin/plugin.video.catchuptvandmore
  
  # Check the plugin with kodi-addon-checker
  kodi-addon-checker:
    name: Kodi-addon-checker
    needs: test-plugin-modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out plugin repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install kodi-addon-checker
        run: pip install kodi-addon-checker==0.0.16
      - name: Run kodi-addon-checker
        run: kodi-addon-checker --branch krypton --allow-folder-id-mismatch ./plugin.video.catchuptvandmore
  
  # Update M3U files
  update-m3u-files:
    name: Update M3U files
    needs: kodi-addon-checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out plugin repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r tools/generate_m3u_files_requirements.txt
      - name: Start M3U files generator
        run: python tools/generate_m3u_files.py
      - name: Push changes
        run: |
          git config user.name 'M3U files generator'
          git config user.email 'github@noreply.github.com'
          git add plugin.video.catchuptvandmore/resources/m3u
          git commit -m "Update M3U files" || echo "No changes to commit"
          git push
  
  # Update repository.catchuptvandmore
  update-repo:
    name: Update repository.catchuptvandmore
    needs: update-m3u-files
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Check out repository.catchuptvandmore repository
        uses: actions/checkout@v2
        with:
          repository: Catch-up-TV-and-More/repository.catchuptvandmore
          token: ${{ secrets.GITHUB_ACTIONS_ACCESS_TOKEN }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Configure git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'github@noreply.github.com'
      - name: Update all repositories
        run: ./update_all_repos.sh
  
  # Test the plugin with our Kodi simulator
  kodi-simulator-1:
    name: "Explore random replay channel #1"
    needs: update-repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out plugin repository
        uses: actions/checkout@v2
        with:
          path: plugin.video.catchuptvandmore
      - name: Check out simulator repository
        uses: actions/checkout@v2
        with:
          path: simulator
          repository: Catch-up-TV-and-More/catchuptvandmore-test
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: simulator
        run: pip install -r requirements.txt
      - name: Start catchuptvandmore-test
        working-directory: simulator
        run: python main.py -c configs/5_explore_random_replay_channel_random_country.json
      
  kodi-simulator-2:
    name: "Explore random website"
    needs: kodi-simulator-1
    runs-on: ubuntu-latest
    steps:
      - name: Check out plugin repository
        uses: actions/checkout@v2
        with:
          path: plugin.video.catchuptvandmore
      - name: Check out simulator repository
        uses: actions/checkout@v2
        with:
          path: simulator
          repository: Catch-up-TV-and-More/catchuptvandmore-test
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: simulator
        run: pip install -r requirements.txt
      - name: Start catchuptvandmore-test
        working-directory: simulator
        run: python main.py -c configs/6_explore_random_website.json
